# 站点名
site_name: HCI Middleware

# 主题
theme: readthedocs

nav:
  - Home: index.md
  - 'Chipset': boards/Chipset.md
  - 'HCI':
    - 'Data Format': HCI_dataformat.md
    - 'Transport': HCI_Tramsport.md
  - 'Others':
    - 'qemu运行BLE': qemu.md
    - 'ubuntu18.04 rtthread qemu 环境搭建': rtthread_ubuntu18.04_qemu环境搭建.md
    - 'rtthread qemu ble 环境': rtthread_qemu_ble.md
    - 'testcases': testcases.md
    - 'ART-Pi 蓝牙开发最小环境': artpi_minimal_environment.md
    

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 3